name: "Hello GHA"
on:
  push:
    branches:
      - master
jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say Hello
        run: |
          echo "Hello world"
      - name: Show today
        run: |
          date
      - name: Show folder contents
        run: |
          ls -l
      - name: Show folder path
        run: |
          pwd
